// Generated by gencpp from file planner/Control.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_CONTROL_H
#define PLANNER_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : omega(0.0)
    , a(0.0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : omega(0.0)
    , a(0.0)  {
  (void)_alloc;
    }



   typedef double _omega_type;
  _omega_type omega;

   typedef double _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::planner::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::planner::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::planner::Control > ControlPtr;
typedef boost::shared_ptr< ::planner::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::Control_<ContainerAllocator1> & lhs, const ::planner::Control_<ContainerAllocator2> & rhs)
{
  return lhs.omega == rhs.omega &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::Control_<ContainerAllocator1> & lhs, const ::planner::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planner::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c838c8a33ea16d85216ae4e8104522a9";
  }

  static const char* value(const ::planner::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc838c8a33ea16d85ULL;
  static const uint64_t static_value2 = 0x216ae4e8104522a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/Control";
  }

  static const char* value(const ::planner::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 omega\n"
"float64 a\n"
;
  }

  static const char* value(const ::planner::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.omega);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::Control_<ContainerAllocator>& v)
  {
    s << indent << "omega: ";
    Printer<double>::stream(s, indent + "  ", v.omega);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_CONTROL_H
